version: '3.9'

networks:
  nginx_proxy_manager_default:
    driver: bridge
    name: nginx_proxy_manager_default

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-site-web
    ports:
      - "45455:5000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - nginx_proxy_manager_default  # Connect app to the custom network
