# .github/workflows/docker-publish.yml
name: Build & Publish Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/my-site-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Capture UTC timestamp
        # e.g. 20250716T142305Z
        run: echo "TIMESTAMP=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GHCR_90_DAYS_TO_LIVE }}

      - name: Build & push image
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ env.TIMESTAMP }}

      - name: Expose image digest
        run: echo "digest=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT
